name: peekanapp
description: Get details about an app on the Google Play Store and Apple App Store.
version: 0.0.2
homepage: https://github.com/jozsefsallai/dart-peekanapp

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
